name: Check

on:
  push:
    branches: [ trunk ]

env:
  ZIG_VERSION: 0.14.0-dev.1911+3bf89f55c
  VULKAN_SDK_VERSION: 1.3.296.0

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo & submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install wayland-protocols libwayland-dev libxkbcommon-dev # Wayland
        sudo apt-get install libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev # X11

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: ${{env.VULKAN_SDK_VERSION}}
        cache: true

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: ${{env.ZIG_VERSION}}

    - name: Type check
      run: zig build check

  build-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout repo & submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: ${{env.VULKAN_SDK_VERSION}}
        cache: true

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: ${{env.ZIG_VERSION}}

    - name: Type check
      run: zig build check